]name: Python 3.8.14
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.14
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.14
    - name: print directory
      run: pwd
    - name: list all items
      run: ls -rthla 
    - name: Install dependencies
      run: |
        make install
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
